---
# Packages to install via apt
apt_installed_packages:
  - zsh
  - gnome-tweaks
  - wezterm
  - build-essential
  - procps
  - curl
  - file
  - git
  - rpi-imager

# Packages to install via homebrew
homebrew_installed_packages:
  - gcc
  - fzf
  - zplug
  - starship
  - eza
  - bat
  - zoxide
  - ripgrep
  - fd
  - tldr
  - httpie
  - jq
  - gitui
  - neovim
  - go
  - go-task
  - direnv

# Mac Applications to install via homebrew casks
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - raycast
  - obsidian
  - wezterm

# Git config
git_config:
  - name: user.name
    value: Ben Poppy
  - name: init.defaultBranch
    value: main
  - name: pull.rebase
    value: true
  - name: core.editor
    value: nvim

git_personal:
  - ws/ansible-jedi-setup
  - .dotfiles
