---
# Packages to install via apt
apt_installed_packages:
  - zsh
  - gnome-tweaks
  - wezterm
  - build-essential
  - procps
  - curl
  - file
  - git
  - rpi-imager
  - dnsutils

# AppImages to install
app_images:
  - name: obsidian
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.12/Obsidian-1.5.12.AppImage
  - name: ghostty
    url: https://github.com/pkgforge-dev/ghostty-appimage/releases/download/v1.1.3/Ghostty-1.1.3-x86_64.AppImage
  - name: bambu
    url: https://github.com/bambulab/BambuStudio/releases/download/v02.00.01.50/Bambu_Studio_ubuntu-20.04_v02.00.01.50.AppImage

# Packages to install via homebrew
homebrew_installed_packages:
  - gcc
  - stow
  - mise
  - openssl@3

# Mac Applications to install via homebrew casks
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - raycast
  - obsidian
  - wezterm
  - todoist
  - docker
  - dbeaver-community
  - spotify
  - slack
  - hammerspoon
  - hiddenbar
  - brainfm

# Docker settings
docker_users:
  - benpoppy

# Git config
git_config:
  - name: user.name
    value: Ben Poppy
  - name: user.email
    value: me@benpoppy.dev
  - name: init.defaultBranch
    value: main
  - name: pull.rebase
    value: true
  - name: core.editor
    value: nvim

