---
# Packages to install via apt
apt_installed_packages:
  - zsh
  - gnome-tweaks
  - wezterm
  - build-essential
  - procps
  - curl
  - file
  - git
  - rpi-imager
  - dnsutils

# AppImages to install
app_images:
  - name: obsidian
    url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.12/Obsidian-1.5.12.AppImage
  - name: zen
    url: https://github.com/zen-browser/desktop/releases/download/1.0.0-a.39/zen-specific.AppImage

# Packages to install via homebrew
homebrew_installed_packages:
  - gcc
  - fzf
  - zplug
  - starship
  - eza
  - bat
  - zoxide
  - ripgrep
  - fd
  - tldr
  - httpie
  - jq
  - gitui
  - neovim
  - go
  - go-task
  - direnv
  - awscli
  - libyaml
  - mise
  - pipx
  - mongosh
  - zellij
  - terraform
  - terragrunt
  - act
  - sops
  - age
  - k9s
  - dotenv

# Mac Applications to install via homebrew casks
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - raycast
  - obsidian
  - wezterm
  - todoist
  - docker
  - arc
  - google-cloud-sdk
  - zoom
  - dbeaver-community
  - zen-browser
  - spotify
  - slack

# Docker settings
docker_users:
  - benpoppy

# Git config
git_config:
  - name: user.name
    value: Ben Poppy
  - name: user.email
    value: me@benpoppy.dev
  - name: init.defaultBranch
    value: main
  - name: pull.rebase
    value: true
  - name: core.editor
    value: nvim

dots_config:
  - name: status.showUntrackedFiles
    value: "no"
  - name: push.autoSetupRemote
    value: true
